-- ============================================================================
-- MIGRATION 008: CREATE treatment_plans TABLE
-- ============================================================================
-- Purpose: Add treatment_plans table with clinic_id for multi-tenant isolation
-- Date: 2025-11-20
-- Author: PunkClaude + GeminiPunk (RAGE MODE)
-- Reason: Defuse LANDMINE 3 - generateTreatmentPlanV3() references non-existent table
-- ============================================================================

BEGIN;

-- ============================================================================
-- STEP 1: CREATE treatment_plans TABLE
-- ============================================================================

CREATE TABLE IF NOT EXISTS treatment_plans (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  
  -- 🏛️ EMPIRE V2: Multi-tenant isolation (THE SHIELD)
  clinic_id UUID NOT NULL REFERENCES clinics(id) ON DELETE CASCADE,
  
  -- Patient reference
  patient_id UUID NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
  
  -- Treatment plan data (stored as JSONB for flexibility)
  conditions TEXT[] NOT NULL,  -- Array of conditions detected (e.g., ['cavities', 'gum_disease'])
  plan JSONB NOT NULL,         -- Array of treatment recommendations with costs, priorities, etc.
  
  -- Metadata
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_by UUID REFERENCES users(id),
  
  -- Soft delete support
  is_active BOOLEAN DEFAULT TRUE,
  deleted_at TIMESTAMPTZ,
  deleted_by UUID REFERENCES users(id)
);

-- ============================================================================
-- STEP 2: CREATE INDEXES
-- ============================================================================

-- Primary multi-tenant filter index (CRITICAL for performance)
CREATE INDEX idx_treatment_plans_clinic ON treatment_plans(clinic_id);

-- Query by patient
CREATE INDEX idx_treatment_plans_patient ON treatment_plans(patient_id);

-- Active plans only (common filter)
CREATE INDEX idx_treatment_plans_active ON treatment_plans(clinic_id, is_active) 
  WHERE is_active = TRUE AND deleted_at IS NULL;

-- ============================================================================
-- STEP 3: ADD FOREIGN KEY CONSTRAINTS
-- ============================================================================

-- Ensure patient exists in patients table
-- (Already added in table creation with REFERENCES)

-- Ensure clinic exists in clinics table
-- (Already added in table creation with REFERENCES)

-- ============================================================================
-- STEP 4: ADD COMMENTS
-- ============================================================================

COMMENT ON TABLE treatment_plans IS 
  'Treatment plans generated by AI for patients. Multi-tenant isolated by clinic_id.';

COMMENT ON COLUMN treatment_plans.clinic_id IS 
  'EMPIRE V2: Clinic that created this treatment plan. CRITICAL for multi-tenant isolation.';

COMMENT ON COLUMN treatment_plans.plan IS 
  'JSONB array of treatment recommendations. Schema: [{ id, treatmentType, description, estimatedCost, priority, reasoning, confidence, recommendedDate }]';

COMMENT ON COLUMN treatment_plans.conditions IS 
  'Array of patient conditions that triggered this plan (e.g., [''cavities'', ''gum_disease'']).';

-- ============================================================================
-- STEP 5: VERIFICATION
-- ============================================================================

DO $$
DECLARE
  table_exists BOOLEAN;
  clinic_id_exists BOOLEAN;
  fk_count INTEGER;
  index_count INTEGER;
BEGIN
  -- Check table exists
  SELECT EXISTS (
    SELECT FROM information_schema.tables 
    WHERE table_name = 'treatment_plans'
  ) INTO table_exists;
  
  IF NOT table_exists THEN
    RAISE EXCEPTION 'MIGRATION 008 FAILED: treatment_plans table not created';
  END IF;
  
  -- Check clinic_id column exists
  SELECT EXISTS (
    SELECT FROM information_schema.columns
    WHERE table_name = 'treatment_plans' AND column_name = 'clinic_id'
  ) INTO clinic_id_exists;
  
  IF NOT clinic_id_exists THEN
    RAISE EXCEPTION 'MIGRATION 008 FAILED: clinic_id column missing';
  END IF;
  
  -- Check foreign keys
  SELECT COUNT(*) INTO fk_count
  FROM information_schema.table_constraints
  WHERE table_name = 'treatment_plans' AND constraint_type = 'FOREIGN KEY';
  
  IF fk_count < 3 THEN
    RAISE WARNING 'MIGRATION 008: Expected 3 foreign keys, found %', fk_count;
  END IF;
  
  -- Check indexes
  SELECT COUNT(*) INTO index_count
  FROM pg_indexes
  WHERE tablename = 'treatment_plans';
  
  IF index_count < 3 THEN
    RAISE WARNING 'MIGRATION 008: Expected 3+ indexes, found %', index_count;
  END IF;
  
  -- Success message
  RAISE NOTICE '✅ MIGRATION 008 VERIFICATION COMPLETE';
  RAISE NOTICE '   - Table: treatment_plans EXISTS';
  RAISE NOTICE '   - Column: clinic_id EXISTS (uuid, NOT NULL)';
  RAISE NOTICE '   - Foreign Keys: % found', fk_count;
  RAISE NOTICE '   - Indexes: % found', index_count;
  RAISE NOTICE '🏛️ LANDMINE 3 DEFUSED: treatment_plans multi-tenant ready';
END $$;

COMMIT;

-- ============================================================================
-- MIGRATION 008 COMPLETE
-- ============================================================================
-- Treatment plans table created with:
-- ✅ clinic_id column (UUID, NOT NULL, FK to clinics)
-- ✅ patient_id column (UUID, NOT NULL, FK to patients)
-- ✅ Multi-tenant indexes (clinic_id primary filter)
-- ✅ Soft delete support (is_active, deleted_at)
-- ✅ JSONB plan storage (flexible schema)
-- 
-- LANDMINE 3 STATUS: DEFUSED ✅
-- ============================================================================
