/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DentiaCoin__factory } from "./DentiaCoin__factory";
export { DentiaRewards__factory } from "./DentiaRewards__factory";
