"""make_patient_id_nullable_for_global_documents

Revision ID: 46d34f250ae7
Revises: fb0c1dc80bef
Create Date: 2025-08-14 01:54:15.230198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '46d34f250ae7'
down_revision: Union[str, Sequence[str], None] = 'fb0c1dc80bef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_logs')
    op.alter_column('medical_documents', 'patient_id',
               existing_type=sa.UUID(),
               nullable=True,
               comment='Reference to the patient (NULL for global/administrative documents)',
               existing_comment='Reference to the patient')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('medical_documents', 'patient_id',
               existing_type=sa.UUID(),
               nullable=False,
               comment='Reference to the patient',
               existing_comment='Reference to the patient (NULL for global/administrative documents)')
    op.create_table('audit_logs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('patient_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('additional_context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('legal_basis', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('consent_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    # ### end Alembic commands ###
