"""Add legal document deletion system Argentina compliance

Revision ID: 76aada9ec7f3
Revises: fix_enum_values_manual
Create Date: 2025-08-14 05:58:50.388756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '76aada9ec7f3'
down_revision: Union[str, Sequence[str], None] = 'fix_enum_values_manual'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permanent_deletion_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('original_document_id', sa.UUID(), nullable=False),
    sa.Column('original_document_title', sa.String(), nullable=False),
    sa.Column('original_document_category', sa.String(), nullable=False),
    sa.Column('original_patient_id', sa.UUID(), nullable=False),
    sa.Column('original_created_at', sa.DateTime(), nullable=False),
    sa.Column('deletion_request_id', sa.UUID(), nullable=False),
    sa.Column('deletion_reason', sa.String(length=50), nullable=False),
    sa.Column('deletion_justification', sa.Text(), nullable=False),
    sa.Column('requesting_user_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=False),
    sa.Column('legal_basis', sa.String(), nullable=False),
    sa.Column('retention_period_years', sa.Integer(), nullable=False),
    sa.Column('document_age_at_deletion', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('approved_at', sa.DateTime(), nullable=False),
    sa.Column('grace_period_end', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=False),
    sa.Column('compliance_verified', sa.Boolean(), nullable=False),
    sa.Column('verification_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deletion_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('requesting_user_id', sa.UUID(), nullable=False),
    sa.Column('deletion_reason', sa.String(length=50), nullable=False),
    sa.Column('user_justification', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('grace_period_start', sa.DateTime(), nullable=True),
    sa.Column('grace_period_end', sa.DateTime(), nullable=True),
    sa.Column('final_deletion_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('legal_compliance_verified', sa.Boolean(), nullable=True),
    sa.Column('retention_period_met', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['medical_documents.id'], ),
    sa.ForeignKeyConstraint(['requesting_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('audit_logs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('action', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resource_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('resource_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('patient_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('additional_context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('legal_basis', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('consent_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('audit_logs_pkey'))
    )
    op.drop_table('deletion_requests')
    op.drop_table('permanent_deletion_records')
    # ### end Alembic commands ###
