"""Add medical records and documents tables

Revision ID: fb0c1dc80bef
Revises: 001
Create Date: 2025-08-12 12:29:47.360964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb0c1dc80bef'
down_revision: Union[str, Sequence[str], None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_locked',
               existing_type=sa.BOOLEAN(),
               comment='Whether the account is locked due to failed login attempts',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_locked',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='Whether the account is locked due to failed login attempts',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###
